In [11]:
from torch.utils.data import TensorDataset, DataLoader, ConcatDataset
import torch

datasets = []
for i in range(3):
    print(torch.arange(i*10, (i+1)*10))
    datasets.append(TensorDataset(torch.arange(i*10, (i+1)*10)))

dataset = ConcatDataset(datasets)
loader = DataLoader(
    dataset,
    shuffle=False,
    num_workers=0,
    batch_size=2
)

for data in loader:
    print(data)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])
[tensor([0, 1])]
[tensor([2, 3])]
[tensor([4, 5])]
[tensor([6, 7])]
[tensor([8, 9])]
[tensor([10, 11])]
[tensor([12, 13])]
[tensor([14, 15])]
[tensor([16, 17])]
[tensor([18, 19])]
[tensor([20, 21])]
[tensor([22, 23])]
[tensor([24, 25])]
[tensor([26, 27])]
[tensor([28, 29])]
